### ISSUE TITLE
 failed to download the file.

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#1]
$ ansible-galaxy install -p roles nousdefions.STIG-RHEL6 
- downloading role 'STIG-RHEL6', owned by nousdefions
- downloading role from https://github.com/MindPointGroup/RHEL6-STIG/archive/master.tar.gz
- error: failed to download the file.
- nousdefions.STIG-RHEL6 was NOT installed successfully.
- you can use --ignore-errors to skip failed roles.

**Comment by defionscode** [comment]
The proper command is: 
`ansible-galaxy install -p roles nousdefions.STIG-RHEL6,devel`

As galaxy defaults to the master branch. I'll update the docs.

**Comment by bbaassssiiee** [comment]
Please fix the master branch. I use a YML file with roles in integration, in the file requirements.yml I list the roles I use from Galaxy like:

    - src: bbaassssiiee.commoncentos
      path: roles/

    - src: https://github.com/MindPointGroup/RHEL6-STIG
      path: roles/

    - src: geerlingguy.java
      path: roles/

In my build I use this command:
    ansible-galaxy install --force -r requirements.yml

**Comment by shepdelacreme** [comment]
You can use "version" in your requirements.yml file to specify the correct branch.

```
- src: https://github.com/MindPointGroup/RHEL6-STIG
  version: devel
  path: roles/
```

**Comment by defionscode** [comment]
@bbaassssiiee there is no master branch, using the requirements.yml you'll need to specify the version as shown by @shepdelacreme you can specify a branch or a tag in the version parameter.

**Comment by bbaassssiiee** [comment]
Thanks! I didn't know that one. It works here!
