### ISSUE TITLE
Certain tasks require target machines to have Internet access

### ISSUE THREAD

**Issue by Dan0maN** [MindPointGroup/RHEL6-STIG#103]
There are certain tasks that require the target machine to have Internet access.  A good example is V-38476 which pulls down the GPG signature from a pre-defined URL.

I would suggest having a way for the user to optionally supply the required files or override the gpg_key_url variable in order to be able to run this role against machines in 'air-gapped' sites.

**Comment by samdoran** [comment]
This is already possible simply by overriding the default value of `gpg_key_url` to an internal URL or a local file.

**Comment by samdoran** [comment]
Oh, I see. That variable is set via `set_fact`. Yuck. Let me fix that.

**Comment by shepdelacreme** [comment]
Fixed by #108
