### ISSUE TITLE
Deprecation Warning: always_run

### ISSUE THREAD

**Issue by LeamHall** [MindPointGroup/RHEL6-STIG#105]
Receiving a Deprecation Warning that always_run will be removed in Ansible 2.4. Fix is to change "always_run: yes" to "check_mode: no" in (RHEL6-STIG-0.9.3/tasks/ ):

- prelim.yml
- cat1.yml
- cat2.yml
- cat3.yml
- not_automated.yml

**Comment by shepdelacreme** [comment]
Currently working on an updated that will correct this as well as a slew of other updates. Stay tuned.
