### ISSUE TITLE
[Documentation] Not running cat2, cat3 tasks

### ISSUE THREAD

**Issue by LeamHall** [MindPointGroup/RHEL6-STIG#107]
When editing site.yml to change "no" to "yes" for "rhell6_stig_cat2" and "rhel6_stig_cat3", the ansible-playbook still doesn't run those tasks. Could use some guidance on how to make them run and what file to edit so they continue to do so.

**Comment by shepdelacreme** [comment]
Could you paste your command or playbook that is calling the role?

**Comment by LeamHall** [comment]
**Operator Error**: Just figured out that playbooks stop execution on a host once a playbook failure is reached. This run stopped on V-38666.

Thanks!
