### ISSUE TITLE
selinux policy tasks not idempotent - V-51363 (CAT 2) and V-51369 (CAT 3) 

### ISSUE THREAD

**Issue by shepdelacreme** [MindPointGroup/RHEL6-STIG#113]
These two tasks which currently do the same exact thing, report a change on every single run. The CAT2 task V-51363 is supposed to set the state to `enforcing` and the CAT3 task V-51369 is supposed to set the policy to `targeted` (or stronger).

Not sure if this is because: 
- the system needs a reboot for it to take effect?
- the selinux module is not functioning properly?
- other?

**Comment by shepdelacreme** [comment]
Looking at the `/etc/selinux/config` there seems to be an issue with it. Will test if this is the result of the Ansible selinux module mangling it or if there is a problem with the file on the machine prior to run Ansible against it.

File as it is now has no line breaks and looks like:
```
# This file controls the state of SELinux on the system.# SELINUX= can take one of these three values:#	enforcing - SELinux security policy is enforced.#	permissive - SELinux prints warnings instead of enforcing.#	disabled - SELinux is fully disabled.SELINUX=enforcing# SELINUXTYPE= type of policy in use. Possible values are:#	targeted - Only targeted network daemons are protected.#	strict - Full SELinux protection.SELINUXTYPE=targeted
```

Running sestatus reports:
```
SELinux status:                 enabled
SELinuxfs mount:                /selinux
Current mode:                   enforcing
Mode from config file:          error (Success)
Policy version:                 24
Policy from config file:        targeted
```
Not sure in what reality `error (Success)` makes any sense.

**Comment by shepdelacreme** [comment]
Looks like this is an issue in 2.4.0.0

https://github.com/ansible/ansible/issues/30618

**Comment by LeamHall** [comment]
The original RHEL 6 STIG had six different VIDs to do exactly the same thing. That's one reason I tend to shy away from using VIDs as tags, but I do see the use behind it.

**Comment by jamescassell** [comment]
seems to be no longer an issue in ansible-2.4.2.0-2.el7.noarch from rhel extras channel.  I've confirmed that I can change the selinux policy by changing the appropriate variable (`-e rhel6stig_selinux_pol=mls`)

I think this issue can be closed.
