### ISSUE TITLE
Update role to STIG version 1, release 17

### ISSUE THREAD

**Issue by shepdelacreme** [MindPointGroup/RHEL6-STIG#115]
DISA published v1R17: https://iasecontent.disa.mil/stigs/zip/U_RedHat_6_V1R17_STIG.zip

**Comment by shepdelacreme** [comment]
Looks like only a single update needed. Other changed items don't affect this role.
**Updates needed:**
- [ ] V-38666 modified from a CAT 1 to a CAT 2 finding. Following code needs to be moved to CAT 2 file.
https://github.com/MindPointGroup/RHEL6-STIG/blob/e4e266f725a3e6afff67428c1d44f482273ac529/tasks/cat1.yml#L211-L230

**Comment by jamescassell** [comment]
V1R18 came out in January.

**Comment by jamescassell** [comment]
V1R18 is a no-op as far as this role is concerned.  It updates wording for how to check 'rpm -V' output, and switches from checking on-disk firewall configuration to checking in-memory firewall configuration.
