### ISSUE TITLE
gconftool-2 tasks are not idempotent

### ISSUE THREAD

**Issue by jamescassell** [MindPointGroup/RHEL6-STIG#126]
All gconftool-2 tasks run every time without exception.

I have a patch locally that makes these idempotent, and also supports check_mode.

I also see that there's a new upstream ansible module for called 'gconftool2' that would likely do the same thing. The gconftool2 module was also included in ansible 2.3.  It would make sense to rewrite these tasks to use the new module at some point, and it might make sense to merge that change the same time as https://github.com/MindPointGroup/RHEL6-STIG/pull/125. Is it worth sending a pull request for my already existing patch that doesn't use the new module?

**Comment by shepdelacreme** [comment]
If you've already got the fixes done then I think it would be worthwhile to have them merged in before the switch to using the gconftool2 module. That way the fixes will be available in an older version of the role for those that can't upgrade to Ansible 2.3 just yet.

Thanks!

**Comment by jamescassell** [comment]
Yes, confirmed.
