### ISSUE TITLE
RHEL 6 STIG v1r19 released

### ISSUE THREAD

**Issue by LeamHall** [MindPointGroup/RHEL6-STIG#139]
And new benchmark. What tools do you use to compare, besides the MK1 eyeball?

**Comment by LeamHall** [comment]
Iusually find them...lacking...

**Comment by jamescassell** [comment]
- [x]  V-38482 - Added "/etc/pam.d/password-auth" to the check and fix.
- [ ]  V-38497 - Added "/etc/pam.d/password-auth" to the check and fix. (PR incoming)
- [ ]  V-38569 - Added "/etc/pam.d/password-auth" to the check and fix.
- [ ]  V-38570 - Added "/etc/pam.d/password-auth" to the check and fix.
- [ ]  V-38571 - Added "/etc/pam.d/password-auth" to the check and fix.
- [ ]  V-38693 - Added "/etc/pam.d/password-auth" to the check and fix.


Here's a start.  I'm doing some updates and will send a PR.
