### ISSUE TITLE
presence of smbclient is not checked before V-38656 check

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#2]
TASK: [nousdefions.STIG-RHEL6 | V-38656 Low  The system must use SMB client signing for connecting to samba servers using smbclient] *** 
<127.0.0.1> REMOTE_MODULE lineinfile state=present backup=yes dest=/etc/samba/smb.conf regexp='client signing' line='client signing = mandatory' insertafter='\[global\]'
failed: [centos6] => {"failed": true, "rc": 257}
msg: Destination /etc/samba/smb.conf does not exist !

FATAL: all hosts have already failed -- aborting

**Comment by matts-mpg** [comment]
Is samba installed on the server in question? I think we are just missing a conditional to check for it, but want to confirm you do not have it installed on your target server.

**Comment by shepdelacreme** [comment]
This item is one of the CAT 3 (Low) checks that we haven't gotten to yet. It just needs a conditional.

**Comment by bbaassssiiee** [comment]
samba is not installed.

**Comment by bbaassssiiee** [comment]
Verified it. Thanks!
...
when: samba_check.stat.exists
