### ISSUE TITLE
cat2.yml actions using gconftool only when: rhel6stig_xwindows_required

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#23]
I suggest to enable them whenever based on oscap auditing. I could mitigate findings using these:
- name: 'SV-50440r3_rule'
  command: gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type string --set /apps/gnome-screensaver/mode blank-only
- name: 'V-38629 Medium  The graphical desktop environment must set the idle timeout to no more than 15 minutes'
  gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type int --set /apps/gnome-screensaver/idle_delay 15
- name: 'V-38630 Medium  The graphical desktop environment must automatically lock after 15 minutes of inactivity and the system must require user to re-authenticate to unlock the environment'
  gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /apps/gnome-screensaver/idle_activation_enabled true
- name: 'V-38638 Medium  The graphical desktop environment must have automatic lock enabled'
  gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory --type bool --set /apps/gnome-screensaver/lock_enabled true

**Comment by shepdelacreme** [comment]
Fixed by #108
