### ISSUE TITLE
V-38671 Remove sendmail package will also remove cronie from CentOS 6 distros.

### ISSUE THREAD

**Issue by mliudev** [MindPointGroup/RHEL6-STIG#27]
Version: 0.9

I'm running STIG categories 1 and 2 on a webserver running CentOS 6.7. I'm running into this error:
```
Traceback (most recent call last):                                                                                     │ * updates: mirror.web-ster.com
  File "/home/centos/.ansible/tmp/ansible-tmp-1440039562.82-112125137340434/cron", line 2117, in <module>              │Resolving Dependencies
    main()                                                                                                             │--> Running transaction check
  File "/home/centos/.ansible/tmp/ansible-tmp-1440039562.82-112125137340434/cron", line 440, in main                   │---> Package cronie.x86_64 0:1.4.4-15.el6 will be installed
    crontab = CronTab(module, user, cron_file)                                                                         │--> Processing Dependency: dailyjobs for package: cronie-1.4.4-15.el6.x86_64
  File "/home/centos/.ansible/tmp/ansible-tmp-1440039562.82-112125137340434/cron", line 178, in __init__               │--> Processing Dependency: /usr/sbin/sendmail for package: cronie-1.4.4-15.el6.x86_64
    self.read()                                                                                                        │--> Running transaction check
  File "/home/centos/.ansible/tmp/ansible-tmp-1440039562.82-112125137340434/cron", line 199, in read                   │---> Package cronie-anacron.x86_64 0:1.4.4-15.el6 will be installed
    raise CronTabError("Unable to read crontab")                                                                       │--> Processing Dependency: crontabs for package: cronie-anacron-1.4.4-15.el6.x86_64
__main__.CronTabError: Unable to read crontab
```
I've discovered that the CentOS crontab package `cronie` is getting uninstalled when running task `V-38671 Medium  The sendmail package must be removed` because cronie has a dependency on sendmail. However, `cronie` is required for the task beginning with `V-38670`, which fails because cronie is no longer installed. Reinstalling cronie and then running this role fixes the issue but it is undesirable to have to run the role, reinstall cronie, then run the roll again.

**Comment by defionscode** [comment]
My initial thought is to implement a check for the removal of sendmail, and subsequently install postfix as per STIG guidance. Postfix being  present should allow cronie to work I think.

Does reinstalling cronie also reinstall sendmail?

**Comment by mliudev** [comment]
I can verify your initial thoughts. The way I’m getting around this now is by uninstalling sendmail then reinstalling cronie and postfix. Reinstalling cronie does not install sendmail. Installing cronie installed exim instead. I don’t know if installing postfix  and then cronie would also install exim.

**Comment by defionscode** [comment]
I'll need to do some experimentation with this. 

1) Need to check to see if exim gets installed if postfix is installed prior to reinstalling cronie
2) Will evaluate the possibility of using `rpm` with `--no-deps`

Thanks for bringing this up

**Comment by samdoran** [comment]
I just dug into this a bit and I think I've nailed down the behavior. `cronie` requires _either_ sendmail or postfix since the `postfix` package also installs `/usr/sbin/sendmail`. Here is `cronie`'s deplist:

```shell
sdoran@stigtest-cos6 ~> yum deplist cronie
Loaded plugins: fastestmirror
Finding dependencies:
Loading mirror speeds from cached hostfile
 * base: mirror.vtti.vt.edu
 * extras: mirror.atlanticmetro.net
 * updates: mirror.ash.fastserv.com
package: cronie.x86_64 1.4.4-15.el6
...
  dependency: /usr/sbin/sendmail
   provider: sendmail.x86_64 8.14.4-9.el6
   provider: postfix.x86_64 2:2.6.6-6.el6_5
...
```

If _neither_ `sendmail` nor `cronie` are installed, installing `cronie` will install postfix to satisfy the dependency (`exim` comes from EPEL; this was run without EPEL configured as another repo) :

```shell
sdoran@stigtest-cos6 ~> sudo yum install cronie
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.vtti.vt.edu
 * extras: mirror.atlanticmetro.net
 * updates: mirror.ash.fastserv.com
Resolving Dependencies
--> Running transaction check
---> Package cronie.x86_64 0:1.4.4-15.el6 will be installed
--> Processing Dependency: dailyjobs for package: cronie-1.4.4-15.el6.x86_64
--> Processing Dependency: /usr/sbin/sendmail for package: cronie-1.4.4-15.el6.x86_64
--> Running transaction check
---> Package cronie-anacron.x86_64 0:1.4.4-15.el6 will be installed
--> Processing Dependency: crontabs for package: cronie-anacron-1.4.4-15.el6.x86_64
---> Package postfix.x86_64 2:2.6.6-6.el6_5 will be installed
--> Running transaction check
---> Package crontabs.noarch 0:1.10-33.el6 will be installed
--> Finished Dependency Resolution
```

If `sendmail` and `cronie` were explicitly installed (not `postfix`), then removing `sendmail` will remove `cronie`. This is the situation @mliudev is reporting.

```shell
sdoran@stigtest-cos6 ~> rpm -qa | grep -E "(postfix|cronie|sendmail)"
cronie-1.4.4-15.el6.x86_64
cronie-anacron-1.4.4-15.el6.x86_64
sendmail-8.14.4-9.el6.x86_64

sdoran@stigtest-cos6 ~> sudo yum erase sendmail
Loaded plugins: fastestmirror
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package sendmail.x86_64 0:8.14.4-9.el6 will be erased
--> Processing Dependency: /usr/sbin/sendmail for package: cronie-1.4.4-15.el6.x86_64
--> Running transaction check
---> Package cronie.x86_64 0:1.4.4-15.el6 will be erased
--> Processing Dependency: cronie = 1.4.4-15.el6 for package: cronie-anacron-1.4.4-15.el6.x86_64
--> Running transaction check
---> Package cronie-anacron.x86_64 0:1.4.4-15.el6 will be erased
--> Processing Dependency: /etc/cron.d for package: crontabs-1.10-33.el6.noarch
--> Restarting Dependency Resolution with new changes.
--> Running transaction check
---> Package crontabs.noarch 0:1.10-33.el6 will be erased
--> Finished Dependency Resolution
```

If `cronie`, `postfix`, and `sendmail` are all installed, then removing `sendmail` _does not_ remove `cronie`. I believe this is the most desirable situation:

```shell
sdoran@stigtest-cos6 ~> rpm -qa | grep -E "(postfix|cronie|sendmail)"
cronie-1.4.4-15.el6.x86_64
cronie-anacron-1.4.4-15.el6.x86_64
sendmail-8.14.4-9.el6.x86_64
postfix-2.6.6-6.el6_5.x86_64

sdoran@stigtest-cos6 ~> sudo yum erase sendmail
Loaded plugins: fastestmirror
Setting up Remove Process
Resolving Dependencies
--> Running transaction check
---> Package sendmail.x86_64 0:8.14.4-9.el6 will be erased
--> Finished Dependency Resolution
```

I believe the best way to fix this is to ensure `postfix` is installed prior to hitting this task. The question then becomes where should `postfix` be installed? Prelim tasks, or immediately prior to V-38671? Immediately prior to V-38671 will work, currently and after the refactor when tasks are ordered by vuln ID. I'll submit a PR that has the task immediately before V-38671 unless I hear otherwise.

**Comment by mliudev** [comment]
Thanks for looking into this. Your findings are consistent with mine. I have been working around this by installing postfix prior to running this role. Thanks for fixing this.
