### ISSUE TITLE
Role needs to be updated to Revision 8

### ISSUE THREAD

**Issue by defionscode** [MindPointGroup/RHEL6-STIG#30]
Currently it is outdated and needs to be updated to the latest revision

**Comment by bbaassssiiee** [comment]
Only 4 rules break under v8:

* SV-50302r4_rule The system must disable accounts after excessive login failures within a 15-minute interval.
* SV-50312r2_rule IP forwarding for IPv4 must not be enabled, unless the system is a router.
* SV-50374r4_rule The system must disable accounts after three consecutive unsuccessful logon attempts.
* SV-50393r4_rule The system must require administrator action to unlock an account locked by excessive failed login attempts.

**Comment by bbaassssiiee** [comment]
There is a PR with fixes.

**Comment by defionscode** [comment]
Closing in leu of Rev9 issue
