### ISSUE TITLE
V-38546 - Disabling IPv6 incompatible with bonded interfaces

### ISSUE THREAD

**Issue by jcrisologo** [MindPointGroup/RHEL6-STIG#40]
According to https://bugzilla.redhat.com/show_bug.cgi?id=531873, the appropriate way to disable IPv6 is to allow the module to load (by removing "install ipv6 /bin/true") but have the line "options ipv6 disable=1" inside /etc/modprobe.d.  The linked bug is for RHEL 5.4, however we have experienced identical behavior on RHEL 6.7.
The SCAP files also do not check for the "/bin/true" line.

**Comment by defionscode** [comment]
@shepdelacreme what are your thoughts on this?

**Comment by shepdelacreme** [comment]
Confirmed this needs to be updated. Check V-38546 in the STIG says it should only have `options ipv6 disable=1` in the `/etc/modprobe.d/` file. Currently the STIG role includes `install ipv6 /bin/true` as well as the options line. Will fix during the refactor of cat2 tasks.

**Comment by samdoran** [comment]
This has been fixed in [this commit](https://github.com/MindPointGroup/RHEL6-STIG/pull/57/commits/13da33a754df499a8afd0f8e3b97fcfb1e829f1b#diff-f0fb3ff257f2f4d1868646236e4fe699R1412). `/etc/modprobe.d/disable-ipv6.conf` now only includes the line `options ipv6 disable=1`.

**Comment by samdoran** [comment]
Fixed in devel.
