### ISSUE TITLE
Role needs to be updated to Revision 15

### ISSUE THREAD

**Issue by shepdelacreme** [MindPointGroup/RHEL6-STIG#48]
Currently it is outdated and needs to be updated to the latest revision.

http://iasecontent.disa.mil/stigs/zip/Apr2016/U_RedHat_6_V1R11_STIG.zip

**Comment by samdoran** [comment]
From reading through the release notes, there are a few dozen finding updates, no new additions, and V-38462 has been removed. Shouldn't be too much work to get this up to the latest revision.

**Comment by shepdelacreme** [comment]
Fixed by #108
