### ISSUE TITLE
Undefined error in deprecation warning

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#50]
TASK [RHEL6-STIG : V-38685 Low  Temporary accounts must be provisioned with an expiration date] ***
task path: RHEL6-STIG/tasks/cat3.yml:194
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this
 will be a fatal error.. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

**Comment by samdoran** [comment]
I'm going to tackle these along with bare variables in my next pass after I finish the refactor.
