### ISSUE TITLE
V-38580 AUDIT rule causes fatal error

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#58]
While running the role as packer provisioner to create a base box it crashed the build:

virtualbox-iso: TASK [RHEL6-STIG : MEDIUM | V-38580 | AUDIT | The audit system must be configured to audit the loading and unloading of dynamic kernel modules.] ***
    virtualbox-iso: task path: /tmp/packer-provisioner-ansible-local/roles/RHEL6-STIG/tasks/cat2.yml:1701
    virtualbox-iso: fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "egrep -e \"(-w |-F path=)/sbin/insmod\" /etc/audit/audit.rules; egrep -e \"(-w |-F path=)/sbin/modprobe\" /etc/audit/audit.rules; egrep -e \"(-w |-F path=)/sbin/rmmod\" /etc/audit/audit.rules;grep -w \"init_module\" /etc/audit/audit.rules; grep -w \"init_module\" /etc/audit/audit.rules", "delta": "0:00:00.008826", "end": "2016-05-10 22:12:41.606537", "failed": true, "rc": 1, "start": "2016-05-10 22:12:41.597711", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

To replicate:
git clone https://github.com/dockpack/dockpack.git
cd dockpack
make install
packer build -only=virtualbox-iso dockpack-centos6.json

**Comment by samdoran** [comment]
This looks like the audit task is missing `ignore_errors` in the `devel` branch. It's fixed in b12221cb783790754cf8033aa07dfb774b8925a2, which has not been merged in yet.

**Comment by bbaassssiiee** [comment]
Can we have a stable devel or master?

**Comment by defionscode** [comment]
Stable releases are tagged which right now is v0.9, similar to how upstream ansible works

**Comment by bbaassssiiee** [comment]
There is only one release v0.9, all fixes since March 2015 are not in it. RHEL-STIG devel does not look stable at the moment.

**Comment by defionscode** [comment]
You're correct on both accounts. We'll tag a new release once the style and
STIG revision refactor work has been completed.


[image: photo] <http://linkedin.com/in/davilaio>
<http://twitter.com/defionscode>  <http://github.com/defionscode> Jonathan
I. Davila
Principal Architect, Automation Practice, Red Hat, Inc
202.415.1878 // redhat.com // jdavila@redhat.com // Washington, D.C

**Comment by samdoran** [comment]
Fixed in devel.
