### ISSUE TITLE
sshd_config seems to be mangled

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#59]
When I ran the role in packer, at the end I get a problem:

RUNNING HANDLER [RHEL6-STIG : restart ssh] *************************************
    virtualbox-iso: fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "/etc/ssh/sshd_config: line 140: Bad configuration option: 'Ciphers\r\n/etc/ssh/sshd_config: line 141: Bad configuration option: 'IgnoreRhosts\r\n/etc/ssh/sshd_config: line 142: Bad configuration option: 'HostbasedAuthentication\r\n/etc/ssh/sshd_config: line 143: Bad configuration option: 'PermitRootLogin\r\n/etc/ssh/sshd_config: line 144: Bad configuration option: 'Banner\r\n/etc/ssh/sshd_config: line 145: Bad configuration option: 'PrintLastLog\r\n/etc/ssh/sshd_config: terminating, 6 bad configuration options\r\n"}****

**Comment by bbaassssiiee** [comment]
Nested quotes?
 
   - { st: 'present', rx: "'^Banner'", ln: "'Banner /etc/issue'" }

should be:

    - { st: 'present', rx: "'^Banner'", ln: "Banner /etc/issue" }

**Comment by samdoran** [comment]
These ssh tasks are totally broken. They create an invalid `sshd_config` file, which is very bad news.

I have fixed theses tasks as well as added `validate` to the tasks in 5e3acb1c32999ee5cb35d7ed47fb272236d34919

**Comment by bbaassssiiee** [comment]
Why push 'totally broken' code?

**Comment by samdoran** [comment]
I agree with the sentiment. I'm not sure when those changes were added (not pulling out the `git blame`). I just want to get past the refactor and start making forward progress again. `devel` isn't stable. We need a stable branch or tag, which will be created once the code is in line with the standards. Sorry for all the bumps along the way!

**Comment by bbaassssiiee** [comment]
A stable 'develop' and tags for releases, and continuous integration of topic branches.

**Comment by samdoran** [comment]
This is now merged into devel.

**Comment by bbaassssiiee** [comment]
Re-open this one, did you restart sshd? I did and found problems. cat2.yml V-38617 lineinfile should not have those single quotes, the lines in /etc/ssh/sshd_config should be like:

IgnoreRhosts yes

not like:

'IgnoreRhosts yes'

This is what happened when I applied the role:
RUNNING HANDLER [RHEL6-STIG : restart ssh] *************************************
fatal: [centos6]: FAILED! => {"changed": false, "failed": true, "msg": "/etc/ssh/sshd_config: line 144: Bad configuration option: 'Ciphers\r\n/etc/ssh/sshd_config: line 145: Bad configuration option: 'IgnoreRhosts\r\n/etc/ssh/sshd_config: line 146: Bad configuration option: 'HostbasedAuthentication\r\n/etc/ssh/sshd_config: line 147: Bad configuration option: 'PermitRootLogin\r\n/etc/ssh/sshd_config: line 148: Bad configuration option: 'Banner\r\n/etc/ssh/sshd_config: line 149: Bad configuration option: 'PrintLastLog\r\n/etc/ssh/sshd_config: terminating, 6 bad configuration options\r\n"}

**Comment by bbaassssiiee** [comment]
Do you want a pull request for this one?

**Comment by samdoran** [comment]
@bbaassssiiee I'm puzzled how you're still getting the bad single quotes. `sshd` does get restarted per the handler, plus I added a `validate` to both [V-38611](https://github.com/MindPointGroup/RHEL6-STIG/blob/devel/tasks/cat2.yml#L2336) and [V-38617](https://github.com/MindPointGroup/RHEL6-STIG/blob/devel/tasks/cat2.yml#L2435) that would prevent a bad `sshd_config` from being put in place.

I also double-checked the final output in `sshd_config` and the single quotes do not exist.

**Comment by bbaassssiiee** [comment]
my bad, roles_path was unset and RHEL6-STIG was installed elsewhere than I thought.

**Comment by shaunbrady** [comment]
Can we get a galaxy release of this?  I'm not sure if that just uses tags, but either way, I keep getting 0.9:

```
$ tail -n 3 galaxy-role-requirements.yaml

- src: nousdefions.STIG-RHEL6
  version: 0.9.2
$ ansible-galaxy install -r galaxy-role-requirements.yaml -p roles --force
- downloading role 'STIG-RHEL6', owned by nousdefions
 [WARNING]: - nousdefions.STIG-RHEL6 was NOT installed successfully: - the specified version (0.9.2) of nousdefions.STIG-RHEL6 was not found in the list of available versions ([{u'name':
u'v0.9', u'created': u'2015-03-19T13:22:29.626Z', u'url': u'', u'release_date': None, u'modified': u'2015-03-19T13:22:29.741Z', u'related': {}, u'id': 3667, u'active': True,
u'summary_fields': {u'role': {u'id': 2955, u'name': u'STIG-RHEL6'}}}]).

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
$
```

Of note, the 0.9.1 and .2 tags are missing the prepending 'v'.  Not sure if that matters or not.

Thanks!

**Comment by shepdelacreme** [comment]
@shaunbrady This should be fixed now. The problem was that Galaxy hadn't imported the new tags yet. I just ran an update and tested importing 0.9.2 successfully.
