### ISSUE TITLE
verify presence of rhnsd service before chkconfig & service stop

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#6]
I had to mock rhnsd on Centos to make the role work.

TASK: [RHEL6-STIG | V-38478 Low  The Red Hat Network Service (rhnsd) service must not be running, unless using RHN or an RHN Satellite] *** 
<127.0.0.1> REMOTE_MODULE command chkconfig rhnsd off && service rhnsd stop #USE_SHELL
changed: [centos6] => {"changed": true, "cmd": "chkconfig rhnsd off && service rhnsd stop", "delta": "0:00:00.026290", "end": "2015-03-19 20:53:17.012627", "failed": false, "failed_when_result": false, "rc": 0, "start": "2015-03-19 20:53:16.986337", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by shepdelacreme** [comment]
Is this task causing the entire role to fail on CentOS?
