### ISSUE TITLE
pam.py leaves 6 trailing spaces in system-auth and password-auth

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#60]

**Comment by bbaassssiiee** [comment]
oscap test U_RedHat_6_V1R8_STIG_SCAP_1-1_Benchmark fails because of that.

**Comment by defionscode** [comment]
I'll get to this today

**Comment by bbaassssiiee** [comment]
Now I only see trailing spaces on this line:
account      required      pam_faillock.so

**Comment by defionscode** [comment]
Is that using a 'fresh' pam file? Or was it ran against the same as prior?


[image: photo] <http://linkedin.com/in/davilaio>
<http://twitter.com/defionscode>  <http://github.com/defionscode> Jonathan
I. Davila
Principal Architect, Automation Practice, Red Hat, Inc
202.415.1878 // redhat.com // jdavila@redhat.com // Washington, D.C

**Comment by bbaassssiiee** [comment]
That is against a vagrantbox that you can use too:

vagrant init dockpack/centos6
vagrant up

**Comment by bbaassssiiee** [comment]
Thumbs up! The oscap audit passes, YEAH!
Cannot reproduce the spaces anymore
