### ISSUE TITLE
password locking of system accounts not idempotent

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#7]
This reports a change every time...

TASK: [RHEL6-STIG | V-38496 Medium  Default system accounts, other than root, must be locked] *** 
<127.0.0.1> REMOTE_MODULE command passwd -l bin
changed: [centos6] => (item=bin) => {"changed": true, "cmd": ["passwd", "-l", "bin"], "delta": "0:00:00.048010", "end": "2015-03-19 20:52:42.964521", "item": "bin", "rc": 0, "start": "2015-03-19 20:52:42.916511", "stderr": "", "stdout": "Locking password for user bin.\npasswd: Success", "warnings": []}

**Comment by defionscode** [comment]
@bbaassssiiee My latest PR should fix that for you.

**Comment by defionscode** [comment]
@bbaassssiiee @shepdelacreme I see what happened in this last commit. We mistakenly  assumed that all locked accounts would have a `!!` after running `passwd -l` this is not the case as just noticed. Have to think about alternatives on this one.

**Comment by defionscode** [comment]
My initial thought now is that we could check for `/sbin/nologin` in `/etc/passwd` to determine if it is locked, but not 100% sure if that is good enough

**Comment by shepdelacreme** [comment]
I think the problem is you can have either '!' or '!!' signify a locked account and it is dependent on the program used to do the locking. i.e. passwd -l locks with '!!' and usermod -L locks with '!'.

We could use ```passwd -S user1``` to check the status of the accounts before acting on them. It will output something like the following if it is locked.

```user1 LK 2014-08-17 0 99999 7 -1 (Password locked.)```

**Comment by bbaassssiiee** [comment]
Shouldn't this be tackled in Ansible's user module?
    user: name={{item}} state=locked

**Comment by shepdelacreme** [comment]
Yeah...that would be a nice enhancement to the ansible user module but it currently does not support that. States are either present or absent.

**Comment by defionscode** [comment]
Right, that would be nice. @bbaassssiiee I think I'll work on making that PR to ansible-core this week. @shepdelacreme suggestion should suffice. doing some tweaking now.

**Comment by defionscode** [comment]
@bbaassssiiee @shepdelacreme latest PR to fix this https://github.com/MindPointGroup/RHEL6-STIG/pull/11
