### ISSUE TITLE
Installing the devel branch from galaxy fails.

### ISSUE THREAD

**Issue by mliudev** [MindPointGroup/RHEL6-STIG#96]
Tried to install the role using: `ansible-galaxy install -p roles nousdefions.STIG-RHEL6,devel` and got:

```
- downloading role 'STIG-RHEL6', owned by nousdefions
 [WARNING]: - nousdefions.STIG-RHEL6 was NOT installed successfully: - the specified version (devel) of nousdefions.STIG-RHEL6
was not found in the list of available versions ([{u'name': u'v0.9', u'created': u'2015-03-19T13:22:29.626Z', u'url': u'',
u'release_date': None, u'modified': u'2015-03-19T13:22:29.741Z', u'related': {}, u'id': 3667, u'active': True,
u'summary_fields': {u'role': {u'id': 2955, u'name': u'STIG-RHEL6'}}}]).

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Doesn't seem like this has been uploaded yet to galaxy?

**Comment by defionscode** [comment]
Devel will never be in galaxy, only stable releases will get pushed there. We're working out some kinks in our CI build for this role to ensure it's fully functional before tagging a new stabel release and pushing it up to Galaxy. If you're on the mailing list I'll be making an announcement once the new tag is pushed up.

**Comment by mliudev** [comment]
That makes sense, but perhaps the README shouldn't tell users to try that command then? For now I will clone the role instead of grabbing 0.9 which has a bug when using ansible 2.1 when configuring sshd_config.

How can I get onto your mailing list?

**Comment by defionscode** [comment]
Ah, good catch, I'll update that. Sorry for that. 

The mailing list is here https://groups.google.com/forum/#!forum/ansible-lockdown

**Comment by mliudev** [comment]
No problem, thanks. I'll close this.
