### ISSUE TITLE
Bootloader Password

### ISSUE THREAD

**Issue by mclarke19** [MindPointGroup/RHEL6-STIG#98]
I understand that this isn't the best place to post this but I am in dire need of help.  I used this role to lock down a VM and it turns out that I had a type in one of the audit rules that is preventing the VM from booting.  I did not change the rhel6stig_bootloader_password to something other than 'random'.  I misread the description and thought you had to leave it has random if you wanted to be able to access the bootloader.  Is there anyway possible to recover the random password generated by grub-crypt?

**Comment by samdoran** [comment]
@mclarke19 No, unfortunately there is not.

What I've done in situations like this is shutdown that machine, detach its SR, mount it on another VM, and edit the `/boot/grub/grub.conf`. Then, reattach the disk to the original VM and reboot the box.

If it's a physical machine, boot off a USB drive or CD with something like [SystemRescueCD](http://www.system-rescue-cd.org/SystemRescueCd_Homepage), mount the disk, and edit the bootloader so it doesn't contain a password.
